name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Déclenche le workflow sur un push vers la branche 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Spécifie l'environnement d'exécution (ici Ubuntu)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Clone le code du dépôt

      - name: Set up Heroku CLI
        uses: akshnz/heroku-cli-action@v1  # Action pour configurer Heroku CLI
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}  # Utilise la clé API stockée dans les secrets

      - name: Deploy to Heroku
        run: |
          echo "Deploying to Heroku"
          git remote add heroku https://git@heroku.com/<nom-de-ton-app>.git  # Remplace par le nom de ton application Heroku
          git push heroku main  # Déploie sur Heroku via Git
